name: Run tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/java@v4
        with:
          java-version: '24'
          distribution: 'oracle'
          cache: maven

      - name: Build
        run: mvn -B package --file pom.xml